// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as React from "react";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import "/node_modules/flag-icons/css/flag-icons.min.css";
;

import "./globalStyles.css";
;

var domElement = document.querySelector("#root");

if (!(domElement == null)) {
  Client.createRoot(domElement).render(JsxRuntime.jsx(React.StrictMode, {
            children: JsxRuntime.jsx(App.make, {})
          }));
}

export {
  
}
/*  Not a pure module */
